# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: multi_redis 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "multi_redis"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Simon Oulevay"]
  s.date = "2014-01-12"
  s.description = "Allows you to organize your redis calls in separate classes but still execute them atomically with pipelined or multi."
  s.email = "git@alphahydrae.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "lib/multi_redis.rb",
    "lib/multi_redis/context.rb",
    "lib/multi_redis/data.rb",
    "lib/multi_redis/executor.rb",
    "lib/multi_redis/extension.rb",
    "lib/multi_redis/future.rb",
    "lib/multi_redis/operation.rb",
    "lib/multi_redis/step.rb"
  ]
  s.homepage = "http://github.com/AlphaHydrae/multi_redis"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.0"
  s.summary = "Pattern to execute separate redis-rb operations in the same command pipeline or multi/exec."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, ["~> 3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.5"])
      s.add_development_dependency(%q<rake>, ["~> 10.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<rake-version>, ["~> 0.4"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.8"])
      s.add_development_dependency(%q<coveralls>, ["~> 0.7"])
    else
      s.add_dependency(%q<redis>, ["~> 3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.5"])
      s.add_dependency(%q<rake>, ["~> 10.1"])
      s.add_dependency(%q<rspec>, ["~> 2.14"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<rake-version>, ["~> 0.4"])
      s.add_dependency(%q<simplecov>, ["~> 0.8"])
      s.add_dependency(%q<coveralls>, ["~> 0.7"])
    end
  else
    s.add_dependency(%q<redis>, ["~> 3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.5"])
    s.add_dependency(%q<rake>, ["~> 10.1"])
    s.add_dependency(%q<rspec>, ["~> 2.14"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<rake-version>, ["~> 0.4"])
    s.add_dependency(%q<simplecov>, ["~> 0.8"])
    s.add_dependency(%q<coveralls>, ["~> 0.7"])
  end
end

